services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    command: ['postgres', '-c', 'log_statement=all']

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},          
        }
      - SMTP_HOST=
      - SMTP_USERNAME=i
      - SMTP_PASSWORD=
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
