CREATE TABLE galleries (
  id SERIAL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  featured_image_id INT REFERENCES images(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);