CREATE TABLE programs (
    id SERIAL PRIMARY KEY,    
    title VARCHAR(128) NOT NULL,
    text TEXT NOT NULL,
    event_id INTEGER REFERENCES events(id) NOT NULL,
    image_id INTEGER REFERENCES images(id) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);